#pragma once

#include "wireshark_ble.h"

#define NEARBY_BLE_UUID_STR_LEN WIRESHARK_BLE_UUID_STR_LEN
#define NEARBY_BLE_LOCAL_NAME_MAX WIRESHARK_BLE_LOCAL_NAME_MAX
#define NEARBY_BLE_MAX_SERVICE_UUIDS WIRESHARK_BLE_MAX_SERVICE_UUIDS
#define NEARBY_BLE_MAX_SERVICE_DATA WIRESHARK_BLE_MAX_SERVICE_DATA
#define NEARBY_BLE_MAX_MANUFACTURER_DATA WIRESHARK_BLE_MAX_MANUFACTURER_DATA
#define NEARBY_BLE_MATCH_BYTES_MAX WIRESHARK_BLE_MATCH_BYTES_MAX

typedef wireshark_ble_parse_result_t nearby_ble_parse_result_t;
#define NEARBY_BLE_PARSE_OK WIRESHARK_BLE_PARSE_OK
#define NEARBY_BLE_PARSE_PARTIAL WIRESHARK_BLE_PARSE_PARTIAL
#define NEARBY_BLE_PARSE_ERR_ARG WIRESHARK_BLE_PARSE_ERR_ARG
#define NEARBY_BLE_PARSE_ERR_MALFORMED WIRESHARK_BLE_PARSE_ERR_MALFORMED

typedef wireshark_ble_uuid_t nearby_ble_uuid_t;
typedef wireshark_ble_service_data_t nearby_ble_service_data_t;
typedef wireshark_ble_manufacturer_data_t nearby_ble_manufacturer_data_t;
typedef wireshark_ble_discovery_facts_t nearby_ble_discovery_facts_t;

#define nearby_ble_parse_advertisement wireshark_ble_parse_adv
#define nearby_ble_uuid_format wireshark_ble_uuid_format
#define nearby_ble_find_manufacturer_data wireshark_ble_find_manufacturer_data
#define nearby_ble_find_service_data wireshark_ble_find_service_data
#define nearby_ble_has_service_uuid wireshark_ble_has_service_uuid
